### ISSUE TITLE
Use a Local Launch Page

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/btp-dev-guidance#5]
Tutorials: https://developers.sap.com/tutorials/use-local-launch-page.html
--------------------------

Would be great if SAP could promote the community project [cds-launchpad-plugin](https://github.com/geert-janklaps/cds-launchpad-plugin) instead of suggesting a static created page for the launchpad mock.

**Comment by slavipande** [comment]
Closed by a diff flow by mistake. Reopening.

**Comment by slavipande** [comment]
Hi @gregorwolf,

I saw your PR https://github.com/cap-js/incidents-app/pull/58 and the team already started the discussion on this. I'll be closing this issue and let's track the progress in https://github.com/cap-js/incidents-app/pull/58.

Thanks and regards,
Sveto
