### ISSUE TITLE
Build a CAP Application

### ISSUE THREAD

**Issue by miyasuta** [sap-tutorials/btp-dev-guidance#904]
Tutorials: https://developers.sap.com/tutorials/build-cap-app.html
--------------------------

At Step 3, the services are already annotated with `@requires`. However, steps to add test users are explained in the subsequent [tutorial](https://developers.sap.com/tutorials/add-authorization.html#c957e0d5-c64f-4c1e-bcb9-64f55bbe9b5e). If authentication is required at this stage, users will be prompted to log in, but they won't know how to authenticate.
Therefore, I believe the `@requires` annotation should be removed from this tutorial.

**Comment by slavipande** [comment]
Hi @miyasuta,

Thanks for your feedback! 

We've updated the code snippet. Here's how the tutorial looks like now: https://developers.sap.com/tutorials/build-cap-app.html#ba4a0026-578a-4202-a9cc-f16adb7f919b

Hence, I'll be closing this issue.

Best regards,
Sveto
